import torch
from transformers import AutoTokenizer, AutoModel
import matplotlib.pyplot as plt
import umap
import numpy as np
import pandas as pd

tokenizer = AutoTokenizer.from_pretrained("microsoft/deberta-v3-base")
model = AutoModel.from_pretrained("microsoft/deberta-v3-base")
model.eval()

# Example input (replace with your real data)
subjective_sentences = [
    "Delicately, I found it overwhelming.",
    "Historically, I completely disagreed.",
    "Philosophically, it didn\u2019t feel right.",
    "Ethically, the reading prioritizes personal experience.",
    "Morally, I wasn't prepared for that.",
    "Personally, this strikes me as profound.",
    "Professionally, I think it lacks authenticity.",
    "Theologically, the narrative evokes a strong response.",
    "Symbolically, I found the message resonant.",
    "Sociologically, it felt insincere.",
    "Symbolically, I found it overwhelming.",
    "Delicately, I completely disagreed.",
    "Spiritually, it didn\u2019t feel right.",
    "Politically, the reading prioritizes personal experience.",
    "Metaphorically, I wasn't prepared for that.",
    "Intellectually, this strikes me as profound.",
    "Ethically, I think it lacks authenticity.",
    "Theoretically, the narrative evokes a strong response.",
    "Rhetorically, I found the message resonant.",
    "Theoretically, it felt insincere.",
    "Individually, I found it overwhelming.",
    "Ethically, I completely disagreed.",
    "Theologically, it didn\u2019t feel right.",
    "Ideologically, the reading prioritizes personal experience.",
    "Politically, I wasn't prepared for that.",
    "Argumentatively, this strikes me as profound.",
    "Personally, I think it lacks authenticity.",
    "Sensitively, the narrative evokes a strong response.",
    "Individually, I found the message resonant.",
    "Theologically, it felt insincere.",
    "Sensitively, I found it overwhelming.",
    "Sensitively, I completely disagreed.",
    "Theoretically, it didn\u2019t feel right.",
    "Metaphorically, the reading prioritizes personal experience.",
    "Argumentatively, I wasn't prepared for that.",
    "Emotionally, this strikes me as profound.",
    "Respectfully, I think it lacks authenticity.",
    "Historically, the narrative evokes a strong response.",
    "Sociologically, I found the message resonant.",
    "Argumentatively, it felt insincere.",
    "Creatively, I found it overwhelming.",
    "Subjectively, I completely disagreed.",
    "Individually, it didn\u2019t feel right.",
    "Respectfully, the reading prioritizes personal experience.",
    "Politically, I wasn't prepared for that.",
    "Artistically, this strikes me as profound.",
    "Ideologically, I think it lacks authenticity.",
    "Metaphorically, the narrative evokes a strong response.",
    "Historically, I found the message resonant.",
    "Philosophically, it felt insincere.",
    "Morally, I found it overwhelming.",
    "Professionally, I completely disagreed.",
    "Metaphorically, it didn\u2019t feel right.",
    "Historically, the reading prioritizes personal experience.",
    "Subjectively, I wasn't prepared for that.",
    "Existentially, this strikes me as profound.",
    "Rhetorically, I think it lacks authenticity.",
    "Aesthetically, the narrative evokes a strong response.",
    "Sociologically, I found the message resonant.",
    "Ideologically, it felt insincere.",
    "Sociologically, I found it overwhelming.",
    "Culturally, I completely disagreed.",
    "Ideologically, it didn\u2019t feel right.",
    "Professionally, the reading prioritizes personal experience.",
    "Creatively, I wasn't prepared for that.",
    "Artistically, this strikes me as profound.",
    "Emotionally, I think it lacks authenticity.",
    "Symbolically, the narrative evokes a strong response.",
    "Aesthetically, I found the message resonant.",
    "Intellectually, it felt insincere.",
    "Dramatically, I found it overwhelming.",
    "Spiritually, I completely disagreed.",
    "Subjectively, it didn\u2019t feel right.",
    "Sensitively, the reading prioritizes personal experience.",
    "Morally, I wasn't prepared for that.",
    "Philosophically, this strikes me as profound.",
    "Dramatically, I think it lacks authenticity.",
    "Rhetorically, the narrative evokes a strong response.",
    "Argumentatively, I found the message resonant.",
    "Individually, it felt insincere.",
    "Psychologically, I found it overwhelming.",
    "Emotionally, I completely disagreed.",
    "Ethically, it didn\u2019t feel right.",
    "Existentially, the reading prioritizes personal experience.",
    "Spiritually, I wasn't prepared for that.",
    "Aesthetically, this strikes me as profound.",
    "Respectfully, I think it lacks authenticity.",
    "Politically, the narrative evokes a strong response.",
    "Dramatically, I found the message resonant.",
    "Delicately, it felt insincere.",
    "Respectfully, I found it overwhelming.",
    "Symbolically, I completely disagreed.",
    "Subjectively, it didn\u2019t feel right.",
    "Artistically, the reading prioritizes personal experience.",
    "Personally, I wasn't prepared for that.",
    "Existentially, this strikes me as profound.",
    "Artistically, I think it lacks authenticity.",
    "Psychologically, the narrative evokes a strong response.",
    "Personally, I found the message resonant.",
    "Psychologically, it felt insincere."
]
subjective_adverbs = [
    "Emotionally",
    "Ethically",
    "Personally",
    "Aesthetically",
    "Ethically",
    "Personally",
    "Emotionally",
    "Aesthetically",
    "Psychologically",
    "Psychologically",
    "Morally",
    "Morally",
    "Emotionally",
    "Culturally",
    "Culturally",
    "Morally",
    "Psychologically",
    "Morally",
    "Philosophically",
    "Culturally",
    "Emotionally",
    "Aesthetically",
    "Personally",
    "Spiritually",
    "Aesthetically",
    "Personally",
    "Emotionally",
    "Morally",
    "Existentially",
    "Personally",
    "Emotionally",
    "Personally",
    "Culturally",
    "Culturally",
    "Emotionally",
    "Ethically",
    "Aesthetically",
    "Spiritually",
    "Existentially",
    "Ethically",
    "Existentially",
    "Emotionally",
    "Ethically",
    "Morally",
    "Psychologically",
    "Existentially",
    "Philosophically",
    "Spiritually",
    "Psychologically",
    "Spiritually",
    "Morally",
    "Emotionally",
    "Aesthetically",
    "Psychologically",
    "Aesthetically",
    "Psychologically",
    "Spiritually",
    "Existentially",
    "Psychologically",
    "Aesthetically",
    "Morally",
    "Psychologically",
    "Emotionally",
    "Culturally",
    "Personally",
    "Existentially",
    "Ethically",
    "Culturally",
    "Morally",
    "Morally",
    "Psychologically",
    "Aesthetically",
    "Personally",
    "Existentially",
    "Aesthetically",
    "Spiritually",
    "Morally",
    "Emotionally",
    "Philosophically",
    "Spiritually",
    "Personally",
    "Morally",
    "Emotionally",
    "Morally",
    "Philosophically",
    "Aesthetically",
    "Psychologically",
    "Psychologically",
    "Emotionally",
    "Ethically",
    "Existentially",
    "Philosophically",
    "Psychologically",
    "Existentially",
    "Culturally",
    "Culturally",
    "Psychologically",
    "Existentially",
    "Aesthetically",
    "Existentially"
]

objective_sentences = [
    "Lexically, this classification is correct.",
    "Separately, the model failed.",
    "Judicially, the reaction is expected.",
    "Meteorologically, the result is valid.",
    "Bureaucratically, the conclusion is incorrect.",
    "Inversely, it's measurable.",
    "Relatively, the structure is stable.",
    "Energetically, the output is analyzable.",
    "Indirectly, the equation holds.",
    "Progressively, this is a legal distinction.",
    "Semantically, this classification is correct.",
    "Astronomically, the model failed.",
    "Syntactically, the reaction is expected.",
    "Dynamically, the result is valid.",
    "Collectively, the conclusion is incorrect.",
    "Proximally, it's measurable.",
    "Statutorily, the structure is stable.",
    "Inclusively, the output is analyzable.",
    "Neutrally, the equation holds.",
    "Regionally, this is a legal distinction.",
    "Nominally, this classification is correct.",
    "Analytically, the model failed.",
    "Syllabically, the reaction is expected.",
    "Administratively, the result is valid.",
    "Precisely, the conclusion is incorrect.",
    "Constitutionally, it's measurable.",
    "Mechanically, the structure is stable.",
    "Geologically, the output is analyzable.",
    "Medically, the equation holds.",
    "Pragmatically, this is a legal distinction.",
    "Anatomically, this classification is correct.",
    "Globally, the model failed.",
    "Economically, the reaction is expected.",
    "Computationally, the result is valid.",
    "Differentially, the conclusion is incorrect.",
    "Radiologically, it's measurable.",
    "Acoustically, the structure is stable.",
    "Temporally, the output is analyzable.",
    "Empirically, the equation holds.",
    "Isotopically, this is a legal distinction.",
    "Objectively, this classification is correct.",
    "Legally, the model failed.",
    "Robustly, the reaction is expected.",
    "Locally, the result is valid.",
    "Statistically, the conclusion is incorrect.",
    "Logically, it's measurable.",
    "Geometrically, the structure is stable.",
    "Symmetrically, the output is analyzable.",
    "Procedurally, the equation holds.",
    "Oceanographically, this is a legal distinction.",
    "Thermodynamically, this classification is correct.",
    "Fundamentally, the model failed.",
    "Prescriptively, the reaction is expected.",
    "Institutionally, the result is valid.",
    "Technologically, the conclusion is incorrect.",
    "Causally, it's measurable.",
    "Experimentally, the structure is stable.",
    "Regressively, the output is analyzable.",
    "Hydraulically, the equation holds.",
    "Remotely, this is a legal distinction.",
    "Nanotechnologically, this classification is correct.",
    "Spatially, the model failed.",
    "Explicitly, the reaction is expected.",
    "Systematically, the result is valid.",
    "Structurally, the conclusion is incorrect.",
    "Biologically, it's measurable.",
    "Microscopically, the structure is stable.",
    "Categorically, the output is analyzable.",
    "Botanically, the equation holds.",
    "Linearly, this is a legal distinction.",
    "Exclusively, this classification is correct.",
    "Historically, the model failed.",
    "Seismologically, the reaction is expected.",
    "Descriptively, the result is valid.",
    "Uniformly, the conclusion is incorrect.",
    "Clinically, it's measurable.",
    "Algorithmically, the structure is stable.",
    "Physically, the output is analyzable.",
    "Governmentally, the equation holds.",
    "Grammatically, this is a legal distinction.",
    "Predictably, this classification is correct.",
    "Programmatically, the model failed.",
    "Theoretically, the reaction is expected.",
    "Phonetically, the result is valid.",
    "Mathematically, the conclusion is incorrect.",
    "Morphologically, it's measurable.",
    "Directly, the structure is stable.",
    "Quantitatively, the output is analyzable.",
    "Chemically, the equation holds.",
    "Uniformly, this is a legal distinction.",
    "Planetarily, this classification is correct.",
    "Functionally, the model failed.",
    "Asymmetrically, the reaction is expected.",
    "Optically, the result is valid.",
    "Justifiably, the conclusion is incorrect.",
    "Implicitly, it's measurable."
]
objective_adverbs = [
    "Lexically",
    "Separately",
    "Judicially",
    "Meteorologically",
    "Bureaucratically",
    "Inversely",
    "Relatively",
    "Energetically",
    "Indirectly",
    "Progressively",
    "Semantically",
    "Astronomically",
    "Syntactically",
    "Dynamically",
    "Collectively",
    "Proximally",
    "Statutorily",
    "Inclusively",
    "Neutrally",
    "Regionally",
    "Nominally",
    "Analytically",
    "Syllabically",
    "Administratively",
    "Precisely",
    "Constitutionally",
    "Mechanically",
    "Geologically",
    "Medically",
    "Pragmatically",
    "Anatomically",
    "Globally",
    "Economically",
    "Computationally",
    "Differentially",
    "Radiologically",
    "Acoustically",
    "Temporally",
    "Empirically",
    "Isotopically",
    "Objectively",
    "Legally",
    "Robustly",
    "Locally",
    "Statistically",
    "Logically",
    "Geometrically",
    "Symmetrically",
    "Procedurally",
    "Oceanographically",
    "Thermodynamically",
    "Fundamentally",
    "Prescriptively",
    "Institutionally",
    "Technologically",
    "Causally",
    "Experimentally",
    "Regressively",
    "Hydraulically",
    "Remotely",
    "Nanotechnologically",
    "Spatially",
    "Explicitly",
    "Systematically",
    "Structurally",
    "Biologically",
    "Microscopically",
    "Categorically",
    "Botanically",
    "Linearly",
    "Exclusively",
    "Historically",
    "Seismologically",
    "Descriptively",
    "Uniformly",
    "Clinically",
    "Algorithmically",
    "Physically",
    "Governmentally",
    "Grammatically",
    "Predictably",
    "Programmatically",
    "Theoretically",
    "Phonetically",
    "Mathematically",
    "Morphologically",
    "Directly",
    "Quantitatively",
    "Chemically",
    "Uniformly",
    "Planetarily",
    "Functionally",
    "Asymmetrically",
    "Optically",
    "Justifiably",
    "Implicitly"
]

speaker_oriented_sentences = [
    "Confidently, I don\u2019t believe that.",
    "Vaguely, we\u2019re not going to make it.",
    "Rudely, I feel terrible about this.",
    "Allegedly, this should not have happened.",
    "Smartly, I must admit I\u2019m wrong.",
    "Symbolically, it\u2019s hard to believe.",
    "Strangely, I didn\u2019t expect this.",
    "Lovingly, the outcome was predictable.",
    "Hesitantly, I don\u2019t know what to say.",
    "Randomly, this is my honest opinion.",
    "Theologically, I don\u2019t believe that.",
    "Softly, we\u2019re not going to make it.",
    "Wisely, I feel terrible about this.",
    "Curiously, this should not have happened.",
    "Paradoxically, I must admit I\u2019m wrong.",
    "Amazingly, it\u2019s hard to believe.",
    "Seriously, I didn\u2019t expect this.",
    "Intentionally, the outcome was predictable.",
    "Unfortunately, I don\u2019t know what to say.",
    "Assertively, this is my honest opinion.",
    "Anxiously, I don\u2019t believe that.",
    "Disappointingly, we\u2019re not going to make it.",
    "Enthusiastically, I feel terrible about this.",
    "Frankly, this should not have happened.",
    "Undoubtedly, I must admit I\u2019m wrong.",
    "Admittedly, it\u2019s hard to believe.",
    "Tactfully, I didn\u2019t expect this.",
    "Sarcastically, the outcome was predictable.",
    "Evidently, I don\u2019t know what to say.",
    "Deliberately, this is my honest opinion.",
    "Compellingly, I don\u2019t believe that.",
    "Bluntly, we\u2019re not going to make it.",
    "Coincidentally, I feel terrible about this.",
    "Ironically, this should not have happened.",
    "Passionately, I must admit I\u2019m wrong.",
    "Disgustedly, it\u2019s hard to believe.",
    "Predictably, I didn\u2019t expect this.",
    "Shockingly, the outcome was predictable.",
    "Wonderfully, I don\u2019t know what to say.",
    "Unofficially, this is my honest opinion.",
    "Proudly, I don\u2019t believe that.",
    "Jokingly, we\u2019re not going to make it.",
    "Philosophically, I feel terrible about this.",
    "Unjustifiably, this should not have happened.",
    "Warmly, I must admit I\u2019m wrong.",
    "Mysteriously, it\u2019s hard to believe.",
    "Miraculously, I didn\u2019t expect this.",
    "Incidentally, the outcome was predictable.",
    "Arguably, I don\u2019t know what to say.",
    "Clearly, this is my honest opinion.",
    "Remorsefully, I don\u2019t believe that.",
    "Unbelievably, we\u2019re not going to make it.",
    "Personally, I feel terrible about this.",
    "Briefly, this should not have happened.",
    "Explicitly, I must admit I\u2019m wrong.",
    "Funnily, it\u2019s hard to believe.",
    "Genuinely, I didn\u2019t expect this.",
    "Fortunately, the outcome was predictable.",
    "Knowingly, I don\u2019t know what to say.",
    "Tenderly, this is my honest opinion.",
    "Wittily, I don\u2019t believe that.",
    "Sincerely, we\u2019re not going to make it.",
    "Metaphorically, I feel terrible about this.",
    "Weirdly, this should not have happened.",
    "Delightfully, I must admit I\u2019m wrong.",
    "Surprisingly, it\u2019s hard to believe.",
    "Confidentially, I didn\u2019t expect this.",
    "Thankfully, the outcome was predictable.",
    "Arrogantly, I don\u2019t know what to say.",
    "Unapologetically, this is my honest opinion.",
    "Presumably, I don\u2019t believe that.",
    "Naively, we\u2019re not going to make it.",
    "Conceptually, I feel terrible about this.",
    "Frighteningly, this should not have happened.",
    "Boldly, I must admit I\u2019m wrong.",
    "Openly, it\u2019s hard to believe.",
    "Shamelessly, I didn\u2019t expect this.",
    "Literally, the outcome was predictable.",
    "Honestly, I don\u2019t know what to say.",
    "Truthfully, this is my honest opinion.",
    "Convincingly, I don\u2019t believe that.",
    "Respectfully, we\u2019re not going to make it.",
    "Justifiably, I feel terrible about this.",
    "Incredibly, this should not have happened.",
    "Tragically, I must admit I\u2019m wrong.",
    "Expectedly, it\u2019s hard to believe.",
    "Obnoxiously, I didn\u2019t expect this.",
    "Candidly, the outcome was predictable.",
    "Sensibly, I don\u2019t know what to say.",
    "Implicitly, this is my honest opinion.",
    "Obviously, I don\u2019t believe that.",
    "Magically, we\u2019re not going to make it.",
    "Regrettably, I feel terrible about this.",
    "Realistically, this should not have happened.",
    "Accidentally, I must admit I\u2019m wrong.",
    "Emphatically, it\u2019s hard to believe.",
    "Theoretically, I didn\u2019t expect this."
]
speaker_oriented_adverbs = [
    "Confidently",
    "Vaguely",
    "Rudely",
    "Allegedly",
    "Smartly",
    "Symbolically",
    "Strangely",
    "Lovingly",
    "Hesitantly",
    "Randomly",
    "Theologically",
    "Softly",
    "Wisely",
    "Curiously",
    "Paradoxically",
    "Amazingly",
    "Seriously",
    "Intentionally",
    "Unfortunately",
    "Assertively",
    "Anxiously",
    "Disappointingly",
    "Enthusiastically",
    "Frankly",
    "Undoubtedly",
    "Admittedly",
    "Tactfully",
    "Sarcastically",
    "Evidently",
    "Deliberately",
    "Compellingly",
    "Bluntly",
    "Coincidentally",
    "Ironically",
    "Passionately",
    "Disgustedly",
    "Predictably",
    "Shockingly",
    "Wonderfully",
    "Unofficially",
    "Proudly",
    "Jokingly",
    "Philosophically",
    "Unjustifiably",
    "Warmly",
    "Mysteriously",
    "Miraculously",
    "Incidentally",
    "Arguably",
    "Clearly",
    "Remorsefully",
    "Unbelievably",
    "Personally",
    "Briefly",
    "Explicitly",
    "Funnily",
    "Genuinely",
    "Fortunately",
    "Knowingly",
    "Tenderly",
    "Wittily",
    "Sincerely",
    "Metaphorically",
    "Weirdly",
    "Delightfully",
    "Surprisingly",
    "Confidentially",
    "Thankfully",
    "Arrogantly",
    "Unapologetically",
    "Presumably",
    "Naively",
    "Conceptually",
    "Frighteningly",
    "Boldly",
    "Openly",
    "Shamelessly",
    "Literally",
    "Honestly",
    "Truthfully",
    "Convincingly",
    "Respectfully",
    "Justifiably",
    "Incredibly",
    "Tragically",
    "Expectedly",
    "Obnoxiously",
    "Candidly",
    "Sensibly",
    "Implicitly",
    "Obviously",
    "Magically",
    "Regrettably",
    "Realistically",
    "Accidentally",
    "Emphatically",
    "Theoretically"
]


all_sentences = subjective_sentences + objective_sentences + speaker_oriented_sentences
all_adverbs = subjective_adverbs + objective_adverbs + speaker_oriented_adverbs
labels = (["subjective"] * len(subjective_sentences) +
          ["objective"] * len(objective_sentences) +
          ["speaker_oriented"] * len(speaker_oriented_sentences))

# Updated function to find adverb embedding
def get_adverb_embedding(sentence, adverb):
    inputs = tokenizer(sentence, return_tensors="pt", truncation=True)
    with torch.no_grad():
        outputs = model(**inputs).last_hidden_state.squeeze(0)  # [seq_len, hidden_size]

    tokens = tokenizer.convert_ids_to_tokens(inputs["input_ids"].squeeze(0))
    token_strs = [t.lower().replace("##", "") for t in tokens]  # DeBERTa uses WordPiece

    adverb_clean = adverb.lower().strip().replace("##", "")

    # Try to locate exact match
    for idx, token in enumerate(token_strs):
        if adverb_clean in token:
            return outputs[idx].numpy()

    print(f"[SKIP] Adverb '{adverb}' not found in: {tokens}")
    return None

# Compute embeddings
embeddings, new_labels, new_adverbs = [], [], []
for sentence, adverb, label in zip(all_sentences, all_adverbs, labels):
    emb = get_adverb_embedding(sentence, adverb)
    if emb is not None:
        embeddings.append(emb)
        new_labels.append(label)
        new_adverbs.append(adverb)

# UMAP
reducer = umap.UMAP(n_neighbors=10, min_dist=0.2, metric='cosine', random_state=42)
reduced_umap = reducer.fit_transform(embeddings)

df_umap = pd.DataFrame({
    "x": reduced_umap[:, 0],
    "y": reduced_umap[:, 1],
    "label": new_labels,
    "adverb": new_adverbs
})

plt.figure(figsize=(9, 7))
for label in df_umap["label"].unique():
    subset = df_umap[df_umap["label"] == label]
    plt.scatter(subset["x"], subset["y"], label=label, alpha=0.7)
plt.title("UMAP: Contextual Embeddings of Domain and Speaker-Oriented Adverbs")
plt.legend()
plt.tight_layout()
plt.show()

# t-SNE
tsne = TSNE(n_components=2, perplexity=30, random_state=42, metric="cosine")
reduced_tsne = tsne.fit_transform(embeddings)

df_tsne = pd.DataFrame({
    "x": reduced_tsne[:, 0],
    "y": reduced_tsne[:, 1],
    "label": new_labels,
    "adverb": new_adverbs
})

plt.figure(figsize=(9, 7))
for label in df_tsne["label"].unique():
    subset = df_tsne[df_tsne["label"] == label]
    plt.scatter(subset["x"], subset["y"], label=label, alpha=0.7)
plt.title("t-SNE: Contextual Embeddings of Domain and Speaker-Oriented Adverbs")
plt.legend()
plt.tight_layout()
plt.show()